### ISSUE TITLE
Linting not running on certain reports

### ISSUE THREAD

**Issue by ganeshn-gh** [tarides/okra#154]
Here is a report where the linter did not run: https://github.com/tarides/admin/commits/main/weekly/2024/01/Kate.md. There is no tick or cross mark 

<img width="1336" alt="image" src="https://github.com/tarides/okra/assets/95270674/9c651c6f-83f9-41be-8320-6e9f65efda51">

Usually there is one. For example, 

<img width="1316" alt="image" src="https://github.com/tarides/okra/assets/95270674/18ed1d53-d544-46ee-9373-5ca56a50fb1f">

Please can we identify why the linter does not run on certain reports and make sure they run on all the submitted reports.

**Comment by punchagan** [comment]
> Here is a report where the linter did not run: https://github.com/tarides/admin/commits/main/weekly/2024/01/Kate.md. There is no tick or cross mark

GitHub actions run only per "push", rather than per commit. So, when a push has two commits, the GitHub action's status icon will only be shown on the last commit in the push. 

In the example you provided, the lint was performed on the [commit](https://github.com/tarides/admin/commits/main/?after=67809b0b734ff610220e3998768f12c0b4aa4834+218) after the one in your example.  And here is the [result of the lint run](https://github.com/tarides/admin/actions/runs/7547316761/job/20546991436) for the report highlighted in your screenshot.

**Comment by ganeshn-gh** [comment]
Yeah, I got it. Thanks @punchagan
