### ISSUE TITLE
New "standard" Off KR work items cause `okra team aggregate --okr-db` to generate reports that don't pass linter

### ISSUE THREAD

**Issue by rikusilvola** [tarides/okra#173]
Reports created with `okra team aggregate --okr-db` don't pass linter, while without db they do.
```
$ okra team aggregate -C /path/to/admin --okr-db /path/to/admin/data/db.csv -w 01 | okra lint
okra: [WARNING] Work logged on KR marked as "Complete": "Resurrect compaction" ("COMP109")
okra: [WARNING] Conflicting titles:
- "Compaction"
- "Resurrect compaction"
okra: [WARNING] KR ID updated from "No KR" to "ABSENCE":
- "Leave"
- "Leave"
okra: [WARNING] Work logged on KR marked as "Complete": "Increase TSan\226\128\153s platform support" ("#1060")
[ERROR(S)]: <stdin>

In KR "Leave (Absence)":
  No KR ID found. WIs should be in the format "This is a WI (#123)", where 123 is the WI issue ID. Legacy KRs should be in the format "This is a KR (PLAT123)", where PLAT123 is the KR ID. For WIs that don't have an ID yet, use "New WI" and for work without a WI use "No WI".
$ okra team aggregate -C /path/to/admin -w 01 | okra lint
[OK]: <stdin>
```
This is due to the new work items such as [(Absence)](https://github.com/tarides/workitems/issues/1074) which is taken from [workitems](https://github.com/tarides/workitems) issue metadata (ID), which don't match neither KR nor WI patterns, nor are they part of any valid objective.

**Comment by gpetiot** [comment]
@rikusilvola can you confirm that this bug is still present in the last release?
If so, can you share your config.yml file? I cannot reproduce it with the default conf.

**Comment by gpetiot** [comment]
I think it's due to `caretaker` giving weird IDs to some workitems in the past, somehow "Leave" has the ID "Absence" instead of https://github.com/tarides/workitems/issues/1074, and caretaker doesn't upgrade existing entries in the generated db.csv (even if IDs don't match).

I don't know how to fix that in caretaker for now.

But the issue will fix itself once we start reporting on objectives instead of workitems (reports will have to be manually fixed).

**Comment by gpetiot** [comment]
There is a workaround which is to use a correct ID instead of "Absence", I opened #223
