### ISSUE TITLE
Surprising behavior of okra cat --include-objectives

### ISSUE THREAD

**Issue by jmid** [tarides/okra#258]
Consider the following weekly (weekly/2024/23/eng2.md):
```
# Last Week

- Property-Based Testing for Multicore (#558)
  - @eng2 (3 days)
  - Foo foo

- Release wasm_of_ocaml (#604)
  - @eng2 (1 day)
  - Foo bar coordination meeting

- Learning
  - @eng2 (1 day)
  - Foo
  - Bar
```

Note: It exclusively uses objectives and standard categories - not WIs, and lints cleanly:
```
admin$ okra --version
2.0.1
admin$ okra lint -C . -e weekly/2024/23/eng2.md
[OK]: weekly/2024/23/eng2.md
```

However when I try to extract relevant activity on an objective I somehow get the entire thing:
```
admin$ okra cat -C . -e --include-objectives="#604" weekly/2024/23/eng2.md
# Last Week

- Property-Based Testing for Multicore (#558)
  - @eng2 (3 days)
  - Foo foo

- Release wasm_of_ocaml (#604)
  - @eng2 (1 day)
  - Foo bar coordination meeting

- Learning
  - @eng2 (1 day)
  - Foo
  - Bar
```

I can use `--include-krs="#604"` as a workaround:
```
admin$ okra cat -C . -e --include-krs="#604" weekly/2024/23/eng2.md
# Last Week

- Release wasm_of_ocaml (#604)
  - @eng2 (1 day)
  - Foo bar coordination meeting
```
This is a bit of a hack, since `Release wasm_of_ocaml (#604)` is an objective - not a WI/KR.
Either I'm misunderstanding the point of `--include-objectives` - or it has a bug.

**Comment by gpetiot** [comment]
Yes indeed, I didn't change the names of the options when I renamed WI into objectives.

This is the meaning that is currently given to the report sections:
- project: level 1 title (`# Abc`)
- objective: level 2 title (`## Abc `)
- kr: item (`- Abc (#123)`)

So I guess, this is normal this is working with `include-krs`.

I don't know if these options and the distinction between the 3 levels are currently used, or if there is only a use for the smallest level.

Accidentally, I just found a bug in the interpretation of the include-objectives/exclude-objectives but that's unrelated to this issue.

**Comment by gpetiot** [comment]
@jmid, here are currently the related options:
- `include-projects`/`exclude-projects`: for level 1 sections
- `include-objectives`/`exclude-objectives`: for level 2 sub-sections
- `include-krs`/`exclude-krs`: for items
- `include-sections`/`exclude-sections`: for projects (md sections) and objectives (md sub-sections)

The first 3 are used for filtering applied to every command, the last one is only applied to the parsing of md files, which sounds redundant.

I propose it becomes:
- `include-sections`/`exclude-sections`: for md sections and sub-sections
- `include-objectives`/`exclude-objectives`: for items

This would be a breaking change of the API, so that will be a 3.0.0 release.

**Comment by gpetiot** [comment]
@jmid @rikusilvola please let me know if you also use filtering of (sub)sections, a lot of code can be pruned if not.

**Comment by gpetiot** [comment]
I'm closing this issue for now. If you would like to rename the options we can open a different issue.
