### ISSUE TITLE
Statistics output on stderr in okra cat

### ISSUE THREAD

**Issue by dra27** [tarides/okra#85]
It would be useful, possibly by file, to have, say, the list of engineer reports processed just as an extra confidence that data were extracted.

e.g.

```
dra@thor:~/admin/okra$ dune exec -- okra cat -e --okr-db=../okr-updates/team-weeklies/db.csv ../tls/42/others.md ../tarides/weekly/2021/42/{antonin,tmcgilchrist}.md ../oclc/weekly/2021/42/{Kate,dra27}.md > ../okr-updates/team-weeklies/2021/42/dra27.md
< okra warnings >
others.md: @TheLortex (new KR); @patricoferris (Plat49)
anontin.md: @MisterDA (Plat49; Plat105)
tmcgilchrist.md: @tmcgilchrist (Plat105; Plat145)
Kate.md: @kit-ty-kate (Plat105; Plat111; Plat124; Plat125)
dra27.md: @dra27 (Comp65; Comp82; Plat105; Plat125; Plat137)
```

**Comment by gpetiot** [comment]
This is not currently possible, the input files are currently all concatenated before being processed by omd, so it's hard to log anything of value here. (and I'm not sure changing that is worth it.)

Since this issue has been opened a long time ago I'm closing it. If this is still something you need, feel free to re-open or comment and we can find a different way to display something useful.
